### ISSUE TITLE
Error on step 27

### ISSUE THREAD

**Issue by Jax-Hax** [babagreensheep/jellyfin-tizen-docker#9]
Every time I try to run this docker container, there is an error on step 27. I cannot run npm ci --no-audit after setting the environment variable! I have tried it on 3 seperate systems, so I am assuming it happens to everyone
I just found the logs:
3739 silly buildTree linking path-root-regex@0.1.2
3740 info lifecycle path-root-regex@0.1.2~preinstall: path-root-regex@0.1.2
3741 info lifecycle path-root-regex@0.1.2~install: path-root-regex@0.1.2
3742 info lifecycle path-root-regex@0.1.2~postinstall: path-root-regex@0.1.2
3743 info lifecycle path-root@0.1.1~install: path-root@0.1.1
3744 info lifecycle path-root@0.1.1~postinstall: path-root@0.1.1
3745 info lifecycle parse-filepath@1.0.2~install: parse-filepath@1.0.2
3746 info lifecycle parse-filepath@1.0.2~postinstall: parse-filepath@1.0.2
3747 info lifecycle fined@1.2.0~install: fined@1.2.0
3748 info lifecycle fined@1.2.0~postinstall: fined@1.2.0
3749 info lifecycle liftoff@3.1.0~install: liftoff@3.1.0
3750 info lifecycle liftoff@3.1.0~postinstall: liftoff@3.1.0
3751 silly buildTree linking interpret@1.4.0
3752 info lifecycle interpret@1.4.0~preinstall: interpret@1.4.0
3753 info lifecycle interpret@1.4.0~install: interpret@1.4.0
3754 info lifecycle interpret@1.4.0~postinstall: interpret@1.4.0
3755 silly buildTree linking copy-props@2.0.5
3756 info lifecycle copy-props@2.0.5~preinstall: copy-props@2.0.5
3757 silly buildTree linking each-props@1.3.2
3758 info lifecycle each-props@1.3.2~preinstall: each-props@1.3.2
3759 info lifecycle each-props@1.3.2~install: each-props@1.3.2
3760 info lifecycle each-props@1.3.2~postinstall: each-props@1.3.2
3761 silly buildTree linking is-plain-object@5.0.0
3762 info lifecycle is-plain-object@5.0.0~preinstall: is-plain-object@5.0.0
3763 info lifecycle is-plain-object@5.0.0~install: is-plain-object@5.0.0
3764 info lifecycle is-plain-object@5.0.0~postinstall: is-plain-object@5.0.0
3765 info lifecycle copy-props@2.0.5~install: copy-props@2.0.5
3766 info lifecycle copy-props@2.0.5~postinstall: copy-props@2.0.5
3767 silly buildTree linking concat-stream@1.6.2
3768 info lifecycle concat-stream@1.6.2~preinstall: concat-stream@1.6.2
3769 silly buildTree linking buffer-from@1.1.2
3770 info lifecycle buffer-from@1.1.2~preinstall: buffer-from@1.1.2
3771 info lifecycle buffer-from@1.1.2~install: buffer-from@1.1.2
3772 info lifecycle buffer-from@1.1.2~postinstall: buffer-from@1.1.2
3773 silly buildTree linking typedarray@0.0.6
3774 info lifecycle typedarray@0.0.6~preinstall: typedarray@0.0.6
3775 info lifecycle typedarray@0.0.6~install: typedarray@0.0.6
3776 info lifecycle typedarray@0.0.6~postinstall: typedarray@0.0.6
3777 info lifecycle concat-stream@1.6.2~install: concat-stream@1.6.2
3778 info lifecycle concat-stream@1.6.2~postinstall: concat-stream@1.6.2
3779 silly buildTree linking array-sort@1.0.0
3780 info lifecycle array-sort@1.0.0~preinstall: array-sort@1.0.0
3781 silly buildTree linking default-compare@1.0.0
3782 info lifecycle default-compare@1.0.0~preinstall: default-compare@1.0.0
3783 silly buildTree linking kind-of@5.1.0
3784 info lifecycle kind-of@5.1.0~preinstall: kind-of@5.1.0
3785 info lifecycle kind-of@5.1.0~install: kind-of@5.1.0
3786 info lifecycle kind-of@5.1.0~postinstall: kind-of@5.1.0
3787 info lifecycle default-compare@1.0.0~install: default-compare@1.0.0
3788 info lifecycle default-compare@1.0.0~postinstall: default-compare@1.0.0
3789 silly buildTree linking kind-of@5.1.0
3790 info lifecycle kind-of@5.1.0~preinstall: kind-of@5.1.0
3791 info lifecycle kind-of@5.1.0~install: kind-of@5.1.0
3792 info lifecycle kind-of@5.1.0~postinstall: kind-of@5.1.0
3793 info lifecycle array-sort@1.0.0~install: array-sort@1.0.0
3794 info lifecycle array-sort@1.0.0~postinstall: array-sort@1.0.0
3795 silly linkStuff gulp-cli@2.3.0 has /home/jellyfin/jellyfin-tizen/node_modules/gulp/node_modules as its parent node_modules
3796 verbose linkBins [
3796 verbose linkBins   { gulp: 'bin/gulp.js' },
3796 verbose linkBins   '/home/jellyfin/jellyfin-tizen/node_modules/gulp/node_modules/.bin',
3796 verbose linkBins   false
3796 verbose linkBins ]
3797 silly gently link link does not already exist {
3797 silly gently link   link: '/home/jellyfin/jellyfin-tizen/node_modules/gulp/node_modules/.bin/gulp',
3797 silly gently link   target: '/home/jellyfin/jellyfin-tizen/node_modules/gulp/node_modules/gulp-cli/bin/gulp.js'
3797 silly gently link }
3798 info lifecycle gulp-cli@2.3.0~install: gulp-cli@2.3.0
3799 info lifecycle gulp-cli@2.3.0~postinstall: gulp-cli@2.3.0
3800 silly linkStuff gulp@4.0.2 has /home/jellyfin/jellyfin-tizen/node_modules as its parent node_modules
3801 verbose linkBins [
3801 verbose linkBins   { gulp: 'bin/gulp.js' },
3801 verbose linkBins   '/home/jellyfin/jellyfin-tizen/node_modules/.bin',
3801 verbose linkBins   false
3801 verbose linkBins ]
3802 info lifecycle gulp@4.0.2~install: gulp@4.0.2
3803 info lifecycle gulp@4.0.2~postinstall: gulp@4.0.2
3804 info lifecycle jellyfin-tizen@0.1.0~install: jellyfin-tizen@0.1.0
3805 info lifecycle jellyfin-tizen@0.1.0~postinstall: jellyfin-tizen@0.1.0
3806 verbose lifecycle jellyfin-tizen@0.1.0~postinstall: unsafe-perm in lifecycle true
3807 verbose lifecycle jellyfin-tizen@0.1.0~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jellyfin/jellyfin-tizen/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/jellyfin/tizen-studio/tools/ide/bin:/home/jellyfin/tizen-studio/tools
3808 verbose lifecycle jellyfin-tizen@0.1.0~postinstall: CWD: /home/jellyfin/jellyfin-tizen
3809 silly lifecycle jellyfin-tizen@0.1.0~postinstall: Args: [ '-c', 'gulp' ]
3810 silly lifecycle jellyfin-tizen@0.1.0~postinstall: Returned: code: 1  signal: null
3811 info lifecycle jellyfin-tizen@0.1.0~postinstall: Failed to exec postinstall script
3812 verbose teardown shutting down workers.
3813 info teardown Done in 0s
3814 verbose stack Error: jellyfin-tizen@0.1.0 postinstall: `gulp`
3814 verbose stack Exit status 1
3814 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3814 verbose stack     at EventEmitter.emit (events.js:400:28)
3814 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3814 verbose stack     at ChildProcess.emit (events.js:400:28)
3814 verbose stack     at maybeClose (internal/child_process.js:1088:16)
3814 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
3815 verbose pkgid jellyfin-tizen@0.1.0
3816 verbose cwd /home/jellyfin/jellyfin-tizen
3817 verbose Linux 5.15.0-67-generic
3818 verbose argv "/usr/bin/node" "/usr/bin/npm" "ci" "--no-audit"
3819 verbose node v14.21.3
3820 verbose npm  v6.14.18
3821 error code ELIFECYCLE
3822 error errno 1
3823 error jellyfin-tizen@0.1.0 postinstall: `gulp`
3823 error Exit status 1
3824 error Failed at the jellyfin-tizen@0.1.0 postinstall script.
3824 error This is probably not a problem with npm. There is likely additional logging output above.
3825 verbose exit [ 1, true ]

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/58746600/235827069-94cdea2d-bf17-4fd3-a198-4557341ccfe1.png)

The output of the build error similar to this?

**Comment by Jax-Hax** [comment]
I didn't make it to step 28, it failed on step 27. I tried to use a prebuilt docker image, but it still didn't work. If anyone has a working image please let me know, or maybe it is something to do with my tv?
